version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}   #default PostgreSQL port 
    env_file:
      - .env  #fallback environment variables file 
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env  #fallback environment variables file 

  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:${API_PORT}"
    volumes:
      - .:/code
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  pgdata:

