version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    ports:
      - ${PGPORT}:${PGPORT}   #default PostgreSQL port 
    env_file:
      - .env  #fallback environment variables file    
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:latest"
    container_name: redis
    command: ["redis-server", "--bind", "0.0.0.0"]
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    env_file:
      - .env  #fallback environment variables file    

volumes:
  pgdata:

