# Generated by Django 3.2.10 on 2023-05-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('query_url', models.URLField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('min_magnitude', models.FloatField()),
                ('type', models.CharField(max_length=64)),
                ('order_by', models.CharField(max_length=64)),
                ('metadata', models.JSONField()),
                ('bbox', models.JSONField()),
                ('features', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'earthquake_query',
                'abstract': False,
            },
        ),
    ]
